
# Basic of Numpy

 

In [ ]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3, 5)

In [3]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.shape


(3, 5)

In [14]:
a.dtype

dtype('int32')

In [9]:
a.size

15

In [10]:
type(a)

numpy.ndarray

In [11]:
a.data

In [12]:
a.itemsize

4

In [16]:
print ( np.array([(1.5,2,3), (4,5,6)]))

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [18]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )

In [19]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [21]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [24]:
np.empty((2,3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [26]:
#To create sequences of numbers, NumPy provides the arange function which is analogous to the Python built-in range, but returns an array.

np.arange(10,30,5)

array([10, 15, 20, 25])

In [29]:
from numpy import pi
x = np.linspace( 0, 2*pi, 100 ) 
f = np.sin(x)

In [31]:
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

# Basic Numpy Function

In [32]:

# empty_like

# Return an empty array with shape and type of input.

# ones_like
# Return an array of ones with shape and type of input.

# zeros_like
# Return an array of zeros with shape and type of input.

# full_like
# Return a new array with shape of input filled with value.

# empty
# Return a new uninitialized array.

# ones
# Return a new array setting values to one.

# zeros
# Return a new array setting values to zero.

# full
# Return a new array of given shape filled with value.

In [33]:
a = ([1,2,3], [4,5,6])  

In [37]:
np.empty_like(a)

array([[-1364091952,         645,           0],
       [          0,      131074,           0]])

In [35]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [38]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [41]:
np.full_like(a,1)

array([[1, 1, 1],
       [1, 1, 1]])